In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import regex as re

In [7]:
cust=pd.read_csv('/workspaces/ftu_ds_comp/q11_12/data/cust.csv')
ii=pd.read_csv('/workspaces/ftu_ds_comp/q11_12/data/interaction_interest.csv')
demo=pd.read_csv('/workspaces/ftu_ds_comp/q11_12/data/demographic.csv')

item=pd.read_csv('/workspaces/ftu_ds_comp/q11_12/data/item.csv')
shelf=pd.read_csv('/workspaces/ftu_ds_comp/q11_12/data/shelf.csv')

In [12]:
cust.rename(columns={'holding_the_item_(s)':'holding_item_duration','looking_at_item_(s)':'looking_at_item_duratiion'},inplace=True)
ii.rename(columns={'holding_the_item_(s)':'hold_item','looking_at_item_(s)':'look_at_item'},inplace=True)

,shelf_id,item_id,name,origin,location,weight_(g),price_vnd,nsx,hsd,marketing_strategy,discount,rate,si_id
0,0,0,Bánh Oreo,Vietnam,Cao,120.0,17500,2023-11-14,2024-10-17,False,10,4,0
1,0,1,Bánh Chocopie,Vietnam,Cao,396.0,48000,2023-10-07,2024-09-16,False,0,3,1
2,0,2,Kẹo cao su Cool Air Fresh,Vietnam,Trung bình,40.0,40000,2024-06-02,2026-06-02,False,0,3,2
3,0,3,Bánh mỳ chà bông Kinh đô,Vietnam,Trung bình,80.0,13400,2024-05-02,2026-05-02,False,0,3,3
4,0,4,Bánh trứng Custard,Thái Lan,Trung bình,46.0,17000,2023-10-30,2024-04-16,True,10,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,7,11,Pizza kitkool,Vietnam,Thấp,140.0,33000,2024-04-16,2024-06-10,False,0,4,711
130,7,12,Mý ý SG Food,Vietnam,Thấp,250.0,27000,2024-02-05,2024-09-03,False,0,4,712
131,7,13,Thanh cua Akira,Nhật Bản,Thấp,200.0,58500,2023-10-16,2023-12-19,False,0,4,713
132,7,14,Nước lẩu Barona,Vietnam,Thấp,180.0,32000,2023-12-02,2024-03-02,False,0,4,714
133,7,15,Xúc xích CP,Vietnam,Thấp,450.0,94000,2024-02-21,2024-05-23,False,0,4,715

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   shelf_id            134 non-null    int64
 1   item_id             134 non-null    int64
 2   name                134 non-null    object
 3   origin              134 non-null    object
 4   location            134 non-null    object
 5   weight_(g)          110 non-null    float64
 6   price_vnd           134 non-null    int64
 7   nsx                 100 non-null    object
 8   hsd                 100 non-null    object
 9   marketing_strategy  134 non-null    bool
 10  discount            134 non-null    int64
 11  rate                134 non-null    int64
 12  si_id               134 non-null    int64
dtypes: bool(1), float64(1), int64(6), object(5)
memory usage: 12.8+ KB